"""ux additions: gamification fields and practice tables

Revision ID: 5f32b9bc0701
Revises: a9b476d49784
Create Date: 2026-03-24 00:14:39.270586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f32b9bc0701'
down_revision: Union[str, None] = 'a9b476d49784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=1000), nullable=False),
    sa.Column('hint', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_prompts_topic'), 'practice_prompts', ['topic'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('user_text', sa.String(length=5000), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.add_column('user_stats', sa.Column('xp_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_stats', sa.Column('daily_xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_stats', sa.Column('daily_answered_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_stats', sa.Column('daily_correct_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_stats', sa.Column('daily_goal_completed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('daily_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_goal')
    op.drop_column('users', 'goal')
    op.drop_column('user_stats', 'daily_goal_completed_at')
    op.drop_column('user_stats', 'daily_correct_count')
    op.drop_column('user_stats', 'daily_answered_count')
    op.drop_column('user_stats', 'daily_xp')
    op.drop_column('user_stats', 'xp_total')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_practice_prompts_topic'), table_name='practice_prompts')
    op.drop_table('practice_prompts')
    # ### end Alembic commands ###
